-- Sanitized commercial onboarding requests for the Cloudflare control plane.
-- This table must never store POS tokens, Winerim tokens, client-token values
-- or webhook secrets. Secrets are validated transiently by the Worker.

CREATE TABLE IF NOT EXISTS public.integration_onboarding_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  provider text NOT NULL CHECK (provider IN ('agora', 'revo')),
  location_name text NOT NULL,
  pos_base_url text NOT NULL,
  revo_tenant text,
  status text NOT NULL DEFAULT 'DRAFT'
    CHECK (status IN ('DRAFT', 'READY_FOR_TECHNICAL_REVIEW', 'TECHNICAL_REVIEW', 'APPROVED', 'REJECTED', 'ACTIVATED')),
  ready_for_technical_review boolean NOT NULL DEFAULT false,
  gate_summary jsonb NOT NULL DEFAULT '[]'::jsonb,
  review_packet jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_by text,
  reviewed_by text,
  reviewed_at timestamptz,
  activated_connection_id uuid REFERENCES public.pos_connections(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT integration_onboarding_requests_no_token_payload
    CHECK (
      review_packet::text !~* '(posApiToken|winerimApiToken|revoClientToken|revoWebhookSecret|service_role|authorization|bearer)'
      AND gate_summary::text !~* '(posApiToken|winerimApiToken|revoClientToken|revoWebhookSecret|service_role|authorization|bearer)'
    )
);

ALTER TABLE public.integration_onboarding_requests ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE ON public.integration_onboarding_requests TO service_role;

CREATE INDEX IF NOT EXISTS idx_integration_onboarding_requests_status
  ON public.integration_onboarding_requests(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_integration_onboarding_requests_provider
  ON public.integration_onboarding_requests(provider, created_at DESC);

DROP TRIGGER IF EXISTS update_integration_onboarding_requests_updated_at
  ON public.integration_onboarding_requests;

CREATE TRIGGER update_integration_onboarding_requests_updated_at
  BEFORE UPDATE ON public.integration_onboarding_requests
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

COMMENT ON TABLE public.integration_onboarding_requests IS
  'Sanitized onboarding requests generated by middleware.winerim.wine. Never stores POS/Winerim secrets.';
