import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Database, Download, RefreshCw, Wine } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { reconciliationApi } from "./api";
import type { FleetBinding, ResultRow } from "./types";

const STATES = ["ALL","MATCHED","HISTORY_MISSING","STOCK_MISSING","BOTH_MISSING","STOCK_UNKNOWN","AMBIGUOUS","SOURCE_INCOMPLETE","DELETED_OR_CANCELLED","OPEN"];
const money = (minor: number, currency = "EUR") => new Intl.NumberFormat("es-ES", { style: "currency", currency: currency || "EUR" }).format(minor / 100);
const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Madrid" }).format(new Date());
const monthStart = `${today.slice(0, 7)}-01`;
const restaurantName = (binding: FleetBinding) => String(binding.location_name ?? binding.metadata.restaurantName ?? binding.metadata.name ?? "Restaurante sin nombre");
const label = (binding: FleetBinding) => `${restaurantName(binding)} · ${binding.winerim_restaurant_id == null ? "pendiente de binding" : `ERP ${binding.winerim_restaurant_id}`}`;

function Metric({ title, value, detail, tone = "neutral" }: { title: string; value: string; detail: string; tone?: "neutral" | "good" | "warn" }) {
  return <div className={`rounded-2xl border p-5 shadow-sm ${tone === "good" ? "border-emerald-500/25 bg-emerald-500/5" : tone === "warn" ? "border-amber-500/25 bg-amber-500/5" : "border-border bg-card"}`}><div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{title}</div><div className="mt-2 text-3xl font-semibold text-foreground">{value}</div><div className="mt-1 text-xs text-muted-foreground">{detail}</div></div>;
}

function safe(row: Record<string, unknown> | null, key: string) { return row?.[key] == null ? "—" : String(row[key]); }

export function DailyReconciliationDashboard() {
  const [connectionId, setConnectionId] = useState(""); const [from, setFrom] = useState(monthStart); const [to, setTo] = useState(today); const [state, setState] = useState("ALL");
  const fleet = useQuery({ queryKey: ["reconciliation-v2", "fleet"], queryFn: reconciliationApi.fleet, refetchInterval: false });
  useEffect(() => { if (!connectionId && fleet.data?.bindings.length) setConnectionId((fleet.data.bindings.find((row) => row.status === "ACTIVE") ?? fleet.data.bindings[0]).connection_id); }, [connectionId, fleet.data]);
  const selected = fleet.data?.bindings.find((binding) => binding.connection_id === connectionId);
  const activeBindings = fleet.data?.bindings.filter((row) => row.status === "ACTIVE") ?? [];
  const pendingBindings = fleet.data?.bindings.filter((row) => row.status !== "ACTIVE") ?? [];
  const details = useQuery({ queryKey: ["reconciliation-v2", connectionId, from, to, state], queryFn: () => reconciliationApi.details(connectionId, from, to, state === "ALL" ? undefined : state), enabled: Boolean(connectionId && selected?.status === "ACTIVE" && from && to && from <= to), refetchInterval: false });
  // Totales del rango elegido: suma de los días (period_kind DAY) dentro de [from, to]; nunca semana/mes precalculados.
  const analytics = useMemo(() => (details.data?.aggregates ?? [])
    .filter((row) => row.period_kind === "DAY" && row.category !== "ALL" && row.period_start >= from && row.period_start <= to)
    .map((row) => ({ business_day: row.period_start, category: row.category, revenue_minor: Number(row.revenue_minor), currency: "EUR" as string | null })), [details.data, from, to]);
  const coveredDays = new Set(analytics.map((row) => row.business_day)).size;
  const rows = details.data?.results ?? [];
  const totals = useMemo(() => {
    const latest = analytics.reduce<Record<string, number>>((acc, row) => { acc[row.category] = (acc[row.category] ?? 0) + Number(row.revenue_minor); return acc; }, {});
    const revenue = Object.values(latest).reduce((sum, value) => sum + value, 0); const matched = rows.filter((row) => row.canonical_state === "MATCHED").length;
    const share = (value: number) => revenue ? value / revenue : 0;
    return { revenue, wine: latest.WINE ?? 0, other: latest.OTHER_BEVERAGE ?? 0, food: latest.FOOD ?? 0, unclassified: latest.UNCLASSIFIED ?? 0, share, matched, exceptions: rows.length - matched };
  }, [analytics, rows]);
  const currency = analytics.find((row) => row.currency)?.currency ?? "EUR";
  const rankings = useMemo(() => {
    const references = new Map<string, number>(); const families = new Map<string, number>();
    for (const row of rows) { const line = row.agora_line; if (!line || line.amountMinor == null) continue; const amount = Number(line.amountMinor); const reference = String(line.wineName ?? line.wineId ?? "Sin referencia"); const family = String(line.family ?? "Sin familia"); references.set(reference, (references.get(reference) ?? 0) + amount); families.set(family, (families.get(family) ?? 0) + amount); }
    const top = (values: Map<string, number>) => [...values].sort((a, b) => b[1] - a[1]).slice(0, 8); return { references: top(references), families: top(families) };
  }, [rows]);
  const chart = useMemo(() => Object.values(analytics.reduce<Record<string, Record<string, number | string>>>((acc, row) => { const day = row.business_day; const target = acc[day] ?? { day, WINE: 0, OTHER_BEVERAGE: 0, FOOD: 0, UNCLASSIFIED: 0 }; target[row.category] = Number(row.revenue_minor) / 100; acc[day] = target; return acc; }, {})).sort((a, b) => String(a.day).localeCompare(String(b.day))), [analytics]);
  const completeStreams = details.data?.coverage.filter((item) => item.coverage_complete).length ?? 0; const streamCount = details.data?.coverage.length ?? 0;

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-3 py-1 text-xs font-medium text-primary"><Database className="h-3.5 w-3.5"/>Auditoría diaria · solo lectura</div><h1 className="text-3xl font-semibold tracking-tight">Ventas, facturación y stock</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Ágora frente a Winerim por línea, con evidencia, cobertura y frescura visibles. Ninguna acción de esta pantalla modifica ventas ni inventario.</p></div><div className="flex gap-2"><button className="rounded-lg border px-3 py-2 text-sm" onClick={() => details.refetch()}><RefreshCw className={`mr-2 inline h-4 w-4 ${details.isFetching ? "animate-spin" : ""}`}/>Actualizar</button><button className="rounded-lg border px-3 py-2 text-sm" onClick={() => reconciliationApi.exportUrl(connectionId, from, to, "csv")}><Download className="mr-2 inline h-4 w-4"/>CSV</button><button className="rounded-lg border px-3 py-2 text-sm" onClick={() => reconciliationApi.exportUrl(connectionId, from, to, "json")}><Download className="mr-2 inline h-4 w-4"/>JSON</button></div></div>
    <div className="grid gap-3 rounded-2xl border bg-card p-4 md:grid-cols-4"><label className="text-xs font-medium text-muted-foreground">Restaurante<select className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm text-foreground" value={connectionId} onChange={(event) => setConnectionId(event.target.value)}><optgroup label={`Conciliación disponible (${activeBindings.length})`}>{activeBindings.map((row) => <option key={row.connection_id} value={row.connection_id}>{label(row)}</option>)}</optgroup><optgroup label={`Pendientes de binding (${pendingBindings.length})`}>{pendingBindings.map((row) => <option key={row.connection_id} value={row.connection_id}>{label(row)}</option>)}</optgroup></select></label><label className="text-xs font-medium text-muted-foreground">Desde<input className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm" type="date" value={from} onChange={(event) => setFrom(event.target.value)}/></label><label className="text-xs font-medium text-muted-foreground">Hasta<input className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm" type="date" value={to} onChange={(event) => setTo(event.target.value)}/></label><label className="text-xs font-medium text-muted-foreground">Estado<select className="mt-1 h-10 w-full rounded-lg border bg-background px-3 text-sm" value={state} onChange={(event) => setState(event.target.value)}>{STATES.map((item) => <option key={item}>{item}</option>)}</select></label></div>
    {selected && selected.status !== "ACTIVE" && <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-4 text-sm text-amber-800"><AlertTriangle className="mr-2 inline h-4 w-4"/><strong>{restaurantName(selected)}</strong> está visible en la flota, pero todavía no tiene binding certificado con Winerim. No se muestran resultados ni se ejecuta conciliación hasta completar esa vinculación.</div>}
    {(fleet.error || details.error) && <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive"><AlertTriangle className="mr-2 inline h-4 w-4"/>{String((fleet.error ?? details.error) instanceof Error ? (fleet.error ?? details.error)?.message : "Error de lectura")}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Facturación total" value={money(totals.revenue, currency)} detail={`${from} → ${to} · ${coveredDays} días con datos`}/><Metric title="Vino" value={money(totals.wine, currency)} detail={`${(totals.share(totals.wine) * 100).toFixed(1)} %`} tone="good"/><Metric title="Otras bebidas" value={money(totals.other, currency)} detail={`${(totals.share(totals.other) * 100).toFixed(1)} %`}/><Metric title="Comida" value={money(totals.food, currency)} detail={`${(totals.share(totals.food) * 100).toFixed(1)} %`}/><Metric title="Sin clasificar" value={money(totals.unclassified, currency)} detail={`${(totals.share(totals.unclassified) * 100).toFixed(1)} %`} tone={totals.unclassified ? "warn" : "good"}/><Metric title="Coincidencias" value={`${totals.matched}`} detail={`${rows.length ? ((totals.matched / rows.length) * 100).toFixed(1) : "0.0"} % de líneas`} tone="good"/><Metric title="Excepciones" value={`${totals.exceptions}`} detail="revisión manual; nunca reparación automática" tone={totals.exceptions ? "warn" : "good"}/><Metric title="Cobertura" value={`${completeStreams}/${streamCount}`} detail={`${selected?.winerim_restaurant_id == null ? "Sin binding" : `ERP ${selected.winerim_restaurant_id}`} · ${details.data?.readCoverage.complete === false ? "lectura truncada" : "lectura completa"}`}/></div>
    <section className="rounded-2xl border bg-card p-5"><div className="mb-4"><h2 className="text-lg font-semibold">Evolución de ingresos por categoría</h2><p className="text-xs text-muted-foreground">Clasificación explícita. Lo no clasificado permanece visible.</p></div><div className="h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="wine" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#7c3aed" stopOpacity={0.45}/><stop offset="95%" stopColor="#7c3aed" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" opacity={0.2}/><XAxis dataKey="day"/><YAxis/><Tooltip formatter={(value: number) => `${value.toFixed(2)} €`}/><Legend/><Area type="monotone" dataKey="WINE" stroke="#7c3aed" fill="url(#wine)"/><Area type="monotone" dataKey="OTHER_BEVERAGE" stroke="#0ea5e9" fillOpacity={0}/><Area type="monotone" dataKey="FOOD" stroke="#22c55e" fillOpacity={0}/><Area type="monotone" dataKey="UNCLASSIFIED" stroke="#f59e0b" fillOpacity={0}/></AreaChart></ResponsiveContainer></div></section>
    <div className="grid gap-4 xl:grid-cols-2">{[["Referencias con más facturación", rankings.references],["Familias con más facturación", rankings.families]].map(([title, values]) => <section key={String(title)} className="rounded-2xl border bg-card p-5"><h2 className="text-lg font-semibold">{String(title)}</h2><div className="mt-4 space-y-2">{(values as Array<[string, number]>).map(([name, amount], index) => <div key={name} className="flex items-center justify-between rounded-lg bg-muted/40 px-3 py-2 text-sm"><span>{index + 1}. {name}</span><strong>{money(amount, currency)}</strong></div>)}{!(values as Array<[string, number]>).length && <p className="text-sm text-muted-foreground">Sin datos completos en el periodo.</p>}</div></section>)}</div>
    <section className="overflow-hidden rounded-2xl border bg-card"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-lg font-semibold">Ágora vs Winerim</h2><p className="text-xs text-muted-foreground">Referencia, formato, factura, hora, unidades, importe y evidencia.</p></div><span className="rounded-full bg-muted px-3 py-1 text-xs">{rows.length} líneas</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-muted/40 text-xs uppercase text-muted-foreground"><tr>{["Fecha","Estado","Referencia","Formato","Factura","Hora Ágora","Uds. Ágora","Importe","Venta Winerim","Uds. Winerim","Acción"].map((head) => <th key={head} className="px-4 py-3 font-medium">{head}</th>)}</tr></thead><tbody>{rows.map((row: ResultRow) => <tr key={row.id} className="border-t"><td className="px-4 py-3">{row.business_day}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs ${row.canonical_state === "MATCHED" ? "bg-emerald-500/10 text-emerald-600" : "bg-amber-500/10 text-amber-700"}`}>{row.canonical_state}</span></td><td className="px-4 py-3 font-medium">{safe(row.agora_line,"wineId")}</td><td className="px-4 py-3">{safe(row.agora_line,"format")}</td><td className="px-4 py-3 font-mono text-xs">{safe(row.agora_line,"documentId")}</td><td className="px-4 py-3">{safe(row.agora_line,"effectiveAt")}</td><td className="px-4 py-3">{safe(row.agora_line,"quantity")}</td><td className="px-4 py-3">{row.agora_line?.amountMinor == null ? "—" : money(Number(row.agora_line.amountMinor))}</td><td className="px-4 py-3">{safe(row.winerim_line,"saleId")}</td><td className="px-4 py-3">{safe(row.winerim_line,"quantity")}</td><td className="max-w-xs px-4 py-3 text-xs text-muted-foreground">{row.manual_action}</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-4 xl:grid-cols-2"><section className="rounded-2xl border bg-card p-5"><h2 className="text-lg font-semibold">Stock actual y movimientos</h2>{Boolean(details.data?.stockItems.length) && <div className="mt-4 overflow-hidden rounded-xl border"><table className="w-full text-sm"><thead className="bg-muted/40 text-xs text-muted-foreground"><tr><th className="px-3 py-2 text-left">Referencia</th><th className="px-3 py-2 text-left">Formato</th><th className="px-3 py-2 text-right">Stock</th><th className="px-3 py-2 text-right">Máx.</th></tr></thead><tbody>{details.data?.stockItems.slice(0, 10).map((item) => <tr key={item.stock_id} className="border-t"><td className="px-3 py-2">{item.wine_name ?? `Vino ${item.wine_id}`}{item.vintage ? ` · ${item.vintage}` : ""}</td><td className="px-3 py-2">{item.format_key ?? "—"}</td><td className="px-3 py-2 text-right font-mono">{item.stock ?? "?"}</td><td className="px-3 py-2 text-right font-mono">{item.max_qty ?? "—"}</td></tr>)}</tbody></table></div>}<div className="mt-4 space-y-2">{(details.data?.stockMovements ?? []).slice(0, 8).map((movement) => <div key={movement.movement_id} className="grid grid-cols-[1fr_auto] gap-3 rounded-xl border p-3 text-sm"><div><div className="font-medium">Vino {movement.wine_id ?? "sin identificar"} · {movement.format_key ?? "sin formato"}</div><div className="text-xs text-muted-foreground">{new Date(movement.recorded_at).toLocaleString()} · {movement.category} · venta {movement.linked_sale_id ?? "—"}</div></div><div className="text-right font-mono">{movement.quantity_before ?? "?"} {movement.quantity_change == null ? "" : `${movement.quantity_change >= 0 ? "+" : ""}${movement.quantity_change}`} → {movement.quantity_after ?? "?"}</div></div>)}{!details.data?.stockMovements.length && <p className="text-sm text-muted-foreground">Sin movimientos en el periodo o lectura todavía incompleta.</p>}</div></section><section className="rounded-2xl border bg-card p-5"><h2 className="text-lg font-semibold">Cobertura y frescura</h2><div className="mt-4 space-y-3">{(details.data?.coverage ?? []).map((item) => <div key={item.stream} className="flex items-center justify-between rounded-xl border p-3"><div><div className="font-medium">{item.stream}</div><div className="text-xs text-muted-foreground">{item.last_complete_at ? new Date(item.last_complete_at).toLocaleString() : "sin lectura completa"}{item.last_error_code ? ` · ${item.last_error_code}` : ""}</div></div>{item.coverage_complete ? <CheckCircle2 className="h-5 w-5 text-emerald-500"/> : <AlertTriangle className="h-5 w-5 text-amber-500"/>}</div>)}</div><div className="mt-5 rounded-xl bg-muted/50 p-4 text-xs text-muted-foreground"><Wine className="mb-2 h-4 w-4"/>El stock actual solo aparece tras habilitar contractualmente <code>/api/v2/stock</code>. Hasta entonces se muestran movimientos y la limitación queda explícita.</div></section></div>
  </div>;
}
